-- Script que contiene los disparadores ( Triggers ) para las tablas de auditoria 
-- David Zambrano
-- 01-11-2017 

-- TRIGGER PARA LA TABLA AREAS
-- INSERT
CREATE OR REPLACE TRIGGER TR_INSERT_AREAS 
AFTER INSERT 
    ON AREAS
    FOR EACH ROW
BEGIN
INSERT INTO AUD_AREAS(
    AREA_CODIGO,
    AREA_NOMBRE,
    AREA_FECHAREGISTRO,
    AREA_REGISTRADOPOR,
    TREGISTRO_AREAS
)
VALUES(
    :NEW.AREA_CODIGO,
    :NEW.AREA_NOMBRE,
    :NEW.AREA_FECHAREGISTRO,
    :NEW.AREA_REGISTRADOPOR,
    'I');
END;
 -- UPDATE
CREATE OR REPLACE TRIGGER TR_UPDATE_AREAS 
AFTER UPDATE 
    ON AREAS
    FOR EACH ROW
BEGIN
INSERT INTO AUD_AREAS(
    AREA_CODIGO,
    AREA_NOMBRE,
    AREA_FECHAREGISTRO,
    AREA_REGISTRADOPOR,
    TREGISTRO_AREAS
)
VALUES(
    :NEW.AREA_CODIGO,
    :NEW.AREA_NOMBRE,
    :NEW.AREA_FECHAREGISTRO,
    :NEW.AREA_REGISTRADOPOR,
    'U');
END;

 -- DELETE
CREATE OR REPLACE TRIGGER TR_DELETE_AREAS 
AFTER DELETE 
    ON AREAS
    FOR EACH ROW
BEGIN
INSERT INTO AUD_AREAS(
    AREA_CODIGO,
    AREA_NOMBRE,
    AREA_FECHAREGISTRO,
    AREA_REGISTRADOPOR,
    TREGISTRO_AREAS
)
VALUES(
    :OLD.AREA_CODIGO,
    :OLD.AREA_NOMBRE,
    :OLD.AREA_FECHAREGISTRO,
    :OLD.AREA_REGISTRADOPOR,
    'D');
END;

-- *******************************************************************
-- TRIGGERS TABLE EPS

-- INSERT
CREATE OR REPLACE TRIGGER TR_INSERT_EPS 
AFTER INSERT 
    ON EPS
    FOR EACH ROW
BEGIN
INSERT INTO AUD_EPS(
    EPS_CODIGO,
    EPS_NOMBRE,
    EPS_FECHAREGISTRO,
    EPS_REGISTRADOPOR,
    TREGISTRO_EPS
)
VALUES(
    :NEW.EPS_CODIGO,
    :NEW.EPS_NOMBRE,
    :NEW.EPS_FECHAREGISTRO,
    :NEW.EPS_REGISTRADOPOR,
    'I');
END;
 -- UPDATE
CREATE OR REPLACE TRIGGER TR_UPDATE_EPS 
AFTER UPDATE 
    ON EPS
    FOR EACH ROW
BEGIN
INSERT INTO AUD_EPS(
    EPS_CODIGO,
    EPS_NOMBRE,
    EPS_FECHAREGISTRO,
    EPS_REGISTRADOPOR,
    TREGISTRO_EPS
)
VALUES(
    :NEW.EPS_CODIGO,
    :NEW.EPS_NOMBRE,
    :NEW.EPS_FECHAREGISTRO,
    :NEW.EPS_REGISTRADOPOR,
    'U');
END;

 -- DELETE
CREATE OR REPLACE TRIGGER TR_DELETE_EPS 
AFTER DELETE 
    ON EPS
    FOR EACH ROW
BEGIN
INSERT INTO AUD_EPS(
    EPS_CODIGO,
    EPS_NOMBRE,
    EPS_FECHAREGISTRO,
    EPS_REGISTRADOPOR,
    TREGISTRO_EPS
)
VALUES(
    :OLD.EPS_CODIGO,
    :OLD.EPS_NOMBRE,
    :OLD.EPS_FECHAREGISTRO,
    :OLD.EPS_REGISTRADOPOR,
    'D');
END;

-- *******************************************************************
-- TRIGGERS TABLE INSTITUCIONES

-- INSERT
CREATE OR REPLACE TRIGGER TR_INSERT_INSTITUCIONES
AFTER INSERT 
    ON INSTITUCIONES
    FOR EACH ROW
BEGIN
INSERT INTO AUD_INSTITUCIONES(
    INSTI_CODIGO,
    INSTI_NOMBREINSTITUCION,
    INSTI_JEFEVOLUNTARIADO,
    INSTI_TELEFONO,
    INSTI_CELULAR,
    INSTI_CORREOELECTRONICO,
    INSTI_FECHAREGISTRO,
    INSTI_REGISTRADOPOR,
    TREGISTRO_INSTITUCIONES
)
VALUES(
    :NEW.INSTI_CODIGO,
    :NEW.INSTI_NOMBREINSTITUCION,
    :NEW.INSTI_JEFEVOLUNTARIADO,
    :NEW.INSTI_TELEFONO,
    :NEW.INSTI_CELULAR,
    :NEW.INSTI_CORREOELECTRONICO,
    :NEW.INSTI_FECHAREGISTRO,
    :NEW.INSTI_REGISTRADOPOR,
    'I');
END;
 -- UPDATE
CREATE OR REPLACE TRIGGER TR_UPDATE_INSTITUCIONES 
AFTER UPDATE 
    ON INSTITUCIONES
    FOR EACH ROW
BEGIN
INSERT INTO AUD_INSTITUCIONES(
    INSTI_CODIGO,
    INSTI_NOMBREINSTITUCION,
    INSTI_JEFEVOLUNTARIADO,
    INSTI_TELEFONO,
    INSTI_CELULAR,
    INSTI_CORREOELECTRONICO,
    INSTI_FECHAREGISTRO,
    INSTI_REGISTRADOPOR,
    TREGISTRO_INSTITUCIONES
)
VALUES(
    :NEW.INSTI_CODIGO,
    :NEW.INSTI_NOMBREINSTITUCION,
    :NEW.INSTI_JEFEVOLUNTARIADO,
    :NEW.INSTI_TELEFONO,
    :NEW.INSTI_CELULAR,
    :NEW.INSTI_CORREOELECTRONICO,
    :NEW.INSTI_FECHAREGISTRO,
    :NEW.INSTI_REGISTRADOPOR,
    'U');
END;

 -- DELETE
CREATE OR REPLACE TRIGGER TR_DELETE_INSTITUCIONES 
AFTER DELETE 
    ON INSTITUCIONES
    FOR EACH ROW
BEGIN
INSERT INTO AUD_INSTITUCIONES(
    INSTI_CODIGO,
    INSTI_NOMBREINSTITUCION,
    INSTI_JEFEVOLUNTARIADO,
    INSTI_TELEFONO,
    INSTI_CELULAR,
    INSTI_CORREOELECTRONICO,
    INSTI_FECHAREGISTRO,
    INSTI_REGISTRADOPOR,
    TREGISTRO_INSTITUCIONES
)
VALUES(
    :OLD.INSTI_CODIGO,
    :OLD.INSTI_NOMBREINSTITUCION,
    :OLD.INSTI_JEFEVOLUNTARIADO,
    :OLD.INSTI_TELEFONO,
    :OLD.INSTI_CELULAR,
    :OLD.INSTI_CORREOELECTRONICO,
    :OLD.INSTI_FECHAREGISTRO,
    :OLD.INSTI_REGISTRADOPOR,
    'D');
END;

-- *******************************************************************
-- TRIGGERS TABLE SUB AREAS

-- INSERT
CREATE OR REPLACE TRIGGER TR_INSERT_SUBAREAS
AFTER INSERT 
    ON SUBAREAS
    FOR EACH ROW
BEGIN
INSERT INTO AUD_SUBAREAS(
    SUBA_CODIGO,
    SUBA_NOMBRE,
    SUBA_FECHAREGISTRO,
    SUBA_REGISTRADOPOR,
    TREGISTRO_SUBAREAS,
    AREA_CODIGO
)
VALUES(
    :NEW.SUBA_CODIGO,
    :NEW.SUBA_NOMBRE,
    :NEW.SUBA_FECHAREGISTRO,
    :NEW.SUBA_REGISTRADOPOR,
    'I',
    :NEW.AREA_CODIGO);
END;
 -- UPDATE
CREATE OR REPLACE TRIGGER TR_UPDATE_SUBAREAS
AFTER UPDATE 
    ON SUBAREAS
    FOR EACH ROW
BEGIN
INSERT INTO AUD_SUBAREAS(
    SUBA_CODIGO,
    SUBA_NOMBRE,
    SUBA_FECHAREGISTRO,
    SUBA_REGISTRADOPOR,
    TREGISTRO_SUBAREAS,
    AREA_CODIGO
)
VALUES(
    :NEW.SUBA_CODIGO,
    :NEW.SUBA_NOMBRE,
    :NEW.SUBA_FECHAREGISTRO,
    :NEW.SUBA_REGISTRADOPOR,
    'U',
    :NEW.AREA_CODIGO);
END;

-- DELETE
CREATE OR REPLACE TRIGGER TR_DELETE_SUBAREAS
AFTER DELETE 
    ON SUBAREAS
    FOR EACH ROW
BEGIN
INSERT INTO AUD_SUBAREAS(
    SUBA_CODIGO,
    SUBA_NOMBRE,
    SUBA_FECHAREGISTRO,
    SUBA_REGISTRADOPOR,
    TREGISTRO_SUBAREAS,
    AREA_CODIGO
)
VALUES(
    :OLD.SUBA_CODIGO,
    :OLD.SUBA_NOMBRE,
    :OLD.SUBA_FECHAREGISTRO,
    :OLD.SUBA_REGISTRADOPOR,
    'D',
    :OLD.AREA_CODIGO);
END;

-- *******************************************************************
-- TRIGGERS TABLE CONTROL HORAS

-- INSERT
CREATE OR REPLACE TRIGGER TR_INSERT_CONTROLHORAS
AFTER INSERT 
    ON CONTROLHORAS
    FOR EACH ROW
BEGIN
INSERT INTO AUD_CONTROLHORAS(
    CONTRO_HORAINGRESO,
    CONTRO_HORASALIDA,
    CONTRO_FECHAREGISTRO,
    CONTRO_REGISTRADOPOR,
    PERSO_CEDULA,
    TREGISTRO_CONTROLHORAS
)
VALUES(
    :NEW.CONTRO_HORAINGRESO,
    :NEW.CONTRO_HORASALIDA,
    :NEW.CONTRO_FECHAREGISTRO,
    :NEW.CONTRO_REGISTRADOPOR,
    :NEW.PERSO_CEDULA,
    'I');
END;
 -- UPDATE
CREATE OR REPLACE TRIGGER TR_UPDATE_CONTROLHORAS
AFTER UPDATE 
    ON CONTROLHORAS
    FOR EACH ROW
BEGIN
INSERT INTO AUD_CONTROLHORAS(
    CONTRO_HORAINGRESO,
    CONTRO_HORASALIDA,
    CONTRO_FECHAREGISTRO,
    CONTRO_REGISTRADOPOR,
    PERSO_CEDULA,
    TREGISTRO_CONTROLHORAS
)
VALUES(
    :NEW.CONTRO_HORAINGRESO,
    :NEW.CONTRO_HORASALIDA,
    :NEW.CONTRO_FECHAREGISTRO,
    :NEW.CONTRO_REGISTRADOPOR,
    :NEW.PERSO_CEDULA,
    'U');
END;

-- DELETE
CREATE OR REPLACE TRIGGER TR_DELETE_CONTROLHORAS
AFTER DELETE 
    ON CONTROLHORAS
    FOR EACH ROW
BEGIN
INSERT INTO AUD_CONTROLHORAS(
    CONTRO_HORAINGRESO,
    CONTRO_HORASALIDA,
    CONTRO_FECHAREGISTRO,
    CONTRO_REGISTRADOPOR,
    PERSO_CEDULA,
    TREGISTRO_CONTROLHORAS
)
VALUES(
    :OLD.CONTRO_HORAINGRESO,
    :OLD.CONTRO_HORASALIDA,
    :OLD.CONTRO_FECHAREGISTRO,
    :OLD.CONTRO_REGISTRADOPOR,
    :OLD.PERSO_CEDULA,
    'D');
END;

-- *******************************************************************
-- TRIGGERS TABLE PERSONAS

-- INSERT
CREATE OR REPLACE TRIGGER TR_INSERT_PERSONAS
AFTER INSERT 
    ON PERSONAS
    FOR EACH ROW
BEGIN
INSERT INTO AUD_PERSONAS(
    PERSO_CEDULA,
    PERSO_TIPO,
    PERSO_NOMBRES,
    PERSO_APELLIDOS,
    PERSO_TELEFONOFIJO,
    PERSO_CELULAR,
    PERSO_USERMAIL,
    PERSO_CONTRASENA,
    PERSO_JEFE,
    PERSO_MODALIDAD,
    PERSO_ESTADO,
    PERSO_FECHAREGISTRO,
    PERSO_REGISTRADOPOR,
    EPS_CODIGO,
    INSTI_CODIGO,
    TREGISTRO_PERSONAS,
    PERSO_CANTHORAS
)
VALUES(
    :NEW.PERSO_CEDULA,
    :NEW.PERSO_TIPO,
    :NEW.PERSO_NOMBRES,
    :NEW.PERSO_APELLIDOS,
    :NEW.PERSO_TELEFONOFIJO,
    :NEW.PERSO_CELULAR,
    :NEW.PERSO_USERMAIL,
    :NEW.PERSO_CONTRASENA,
    :NEW.PERSO_JEFE,
    :NEW.PERSO_MODALIDAD,
    :NEW.PERSO_ESTADO,
    :NEW.PERSO_FECHAREGISTRO,
    :NEW.PERSO_REGISTRADOPOR,
    :NEW.EPS_CODIGO,
    :NEW.INSTI_CODIGO,
    'I',
    :NEW.PERSO_CANTHORAS);
END;
 -- UPDATE
CREATE OR REPLACE TRIGGER TR_UPDATE_PERSONAS
AFTER UPDATE 
    ON PERSONAS
    FOR EACH ROW
BEGIN
INSERT INTO AUD_PERSONAS(
    PERSO_CEDULA,
    PERSO_TIPO,
    PERSO_NOMBRES,
    PERSO_APELLIDOS,
    PERSO_TELEFONOFIJO,
    PERSO_CELULAR,
    PERSO_USERMAIL,
    PERSO_CONTRASENA,
    PERSO_JEFE,
    PERSO_MODALIDAD,
    PERSO_ESTADO,
    PERSO_FECHAREGISTRO,
    PERSO_REGISTRADOPOR,
    EPS_CODIGO,
    INSTI_CODIGO,
    TREGISTRO_PERSONAS,
    PERSO_CANTHORAS
)
VALUES(
    :NEW.PERSO_CEDULA,
    :NEW.PERSO_TIPO,
    :NEW.PERSO_NOMBRES,
    :NEW.PERSO_APELLIDOS,
    :NEW.PERSO_TELEFONOFIJO,
    :NEW.PERSO_CELULAR,
    :NEW.PERSO_USERMAIL,
    :NEW.PERSO_CONTRASENA,
    :NEW.PERSO_JEFE,
    :NEW.PERSO_MODALIDAD,
    :NEW.PERSO_ESTADO,
    :NEW.PERSO_FECHAREGISTRO,
    :NEW.PERSO_REGISTRADOPOR,
    :NEW.EPS_CODIGO,
    :NEW.INSTI_CODIGO,
    'U',
    :NEW.PERSO_CANTHORAS);
END;

-- DELETE
CREATE OR REPLACE TRIGGER TR_DELETE_PERSONAS
AFTER DELETE 
    ON PERSONAS
    FOR EACH ROW
BEGIN
INSERT INTO AUD_PERSONAS(
    PERSO_CEDULA,
    PERSO_TIPO,
    PERSO_NOMBRES,
    PERSO_APELLIDOS,
    PERSO_TELEFONOFIJO,
    PERSO_CELULAR,
    PERSO_USERMAIL,
    PERSO_CONTRASENA,
    PERSO_JEFE,
    PERSO_MODALIDAD,
    PERSO_ESTADO,
    PERSO_FECHAREGISTRO,
    PERSO_REGISTRADOPOR,
    EPS_CODIGO,
    INSTI_CODIGO,
    TREGISTRO_PERSONAS,
    PERSO_CANTHORAS
)
VALUES(
    :OLD.PERSO_CEDULA,
    :OLD.PERSO_TIPO,
    :OLD.PERSO_NOMBRES,
    :OLD.PERSO_APELLIDOS,
    :OLD.PERSO_TELEFONOFIJO,
    :OLD.PERSO_CELULAR,
    :OLD.PERSO_USERMAIL,
    :OLD.PERSO_CONTRASENA,
    :OLD.PERSO_JEFE,
    :OLD.PERSO_MODALIDAD,
    :OLD.PERSO_ESTADO,
    :OLD.PERSO_FECHAREGISTRO,
    :OLD.PERSO_REGISTRADOPOR,
    :OLD.EPS_CODIGO,
    :OLD.INSTI_CODIGO,
    'D',
    :OLD.PERSO_CANTHORAS);
END;
